name: wf_pr
on:
  workflow_dispatch:
    inputs:
      entorno:
        required: true
        default: dev
        type: choice
        options:
          - dev
          - qa
          - prod

jobs:
  ejecucion_actions:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment: ${{ github.event.inputs.entorno || 'dev' }}
    outputs: 
      nombreVecino: "Jorge"
    steps:
      - name: invocaraction
        id: actiontarea
        uses: DevOpstareas/t1action@main
        with: 
            nombre: ${{ vars.NOMBRE }}
            apellido: ${{ vars.APELLIDO }}
            edad: ${{ vars.EDAD }}
      - name: Mostrar resultados
        run: |
          echo "La multiplicación de la edad es: ${{ steps.actiontarea.outputs.resultado }}" 
      

      - name: Imprimir mensaje
        run: echo "El entorno es ${{ vars.AMBIENTE }}"

  invocarwf:
    uses: DevOpstareas/reusable_workflow/.github/workflows/rwf_t1.yml@main
    with:
      nombre: 'Nancy'

  job_outpts:
    runs-on: ubuntu-latest
    needs: ejecucion_actions
    steps:
      - name: Imprimir output del job ejecucion_actions
        run: echo "El nombre del vecino es ${{ needs.ejecucion_actions.outputs.nombreVecino }}"

      