name: wf_pr

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:
jobs:
  ejecucion_actions:
    runs-on: ubuntu-latest
    environment: ${{github.ref_name == 'develop' && 'dev' || github.ref_name == 'main' && 'prod'}}
    steps:
      - name: Imprimir mensaje
        run: |
          echo "El entorno es ${{ vars.AMBIENTE }}"