name: wf_pr
on:
#  push:
#    branches:
#      - release
  workflow_dispatch:
    inputs:
      entorno:
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - qa
          - prod

jobs:
  entorno:
      runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.entorno || 'dev' }}
    steps:
      - name: Imprimir mensaje
        run: |
          echo El entorno es ${{ vars.AMBIENTE }}

  ejecucion_actions:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: invocaraction
        uses: DevOpstareas/t1action@main
        with:
            nombre: ${{ vars.NOMBRE }}
            apellido: ${{ vars.APELLIDO }}
            edad: ${{ vars.EDAD }}

ejecucion_rwf:
  uses: DevOpstareas/t1workflow/.github/workflows/t1workflow.yml@main 
    with:
      nombre: 'Nancy'
